### ISSUE TITLE
Error deploying project to apigee

### ISSUE THREAD

**Issue by jansinger** [apigee-127/a127#50]
Trying to deploy a project on apigee (OPDK in this case) results in an error:
```
DEBUG=* a127 project deploy -u -a test-online
  nodemon bus new listener: reset (0) +0ms
  nodemon bus new listener: reset (0) +3ms
  nodemon bus new listener: quit (0) +16ms
  nodemon bus new listener: quit (0) +1ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +3ms
  true account: test-online +0ms
  true read config file: /Users/jansinger/Sites/md/md-error-proxy/config/default.yaml +4ms
  true failed attempt to read config: /Users/jansinger/Sites/md/md-error-proxy/config/test-online.yaml +1ms
  true writing secrets file: /Users/jansinger/Sites/md/md-error-proxy/config/.a127_secrets +1ms
  true writing environment: dev-online to /Users/jansinger/Sites/md/md-error-proxy/config/.a127_env +1ms
Deploying project md-error-proxy to test-online...
  true debug enabled. leaving deployment files: /Users/jansinger/Sites/md/md-error-proxy/config/.a127_env,/Users/jansinger/Sites/md/md-error-proxy/config/.a127_secrets +338ms
**Error: Missing required option "environments"**
    at checkProperty (/Users/jansinger/npm/lib/node_modules/apigee-127/node_modules/apigeetool/lib/options.js:117:12)
    at /Users/jansinger/npm/lib/node_modules/apigee-127/node_modules/apigeetool/lib/options.js:89:5
    at /Users/jansinger/npm/lib/node_modules/apigee-127/node_modules/apigeetool/node_modules/async/lib/async.js:181:20
    at Immediate.iterate [as _onImmediate] (/Users/jansinger/npm/lib/node_modules/apigee-127/node_modules/apigeetool/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
This seems to be an issue with a new version of apigeetool expecting a parameter "environments".

**Comment by theganyo** [comment]
Apologies for this. An "upgrade" went wrong. :)  Please reinstall apigee-127 and try again.

**Comment by jansinger** [comment]
Thanks for the quick resolution, it works again!
